objects = [
    "basin",
    "bathroom_product",
    "bed",
    "bedding",
    "blanket",
    "book",
    "bowl",
    "cabinet",
    "ceiling",
    "ceiling_light",
    "chair",
    "chandelier",
    "chopstick",
    "clock",
    "closestool",
    "computer",
    "cookware",
    "cosmetic",
    "cup",
    "curtain",
    "cushion",
    "daily_equipment",
    "decorative_box",
    "desk",
    "dining_table",
    "door",
    "door_handle",
    "doorsill",
    "electric_appliance",
    "floor",
    "floor_lamp",
    "flower",
    "fork",
    "fridge",
    "fruit",
    "hardware_decoration",
    "kettle",
    "kitchenware",
    "knife",
    "menorah",
    "microwave",
    "mirror",
    "office_supply",
    "ornament",
    "other_cooker",
    "painting",
    "picture_frame",
    "pillar",
    "pillow",
    "plate",
    "range_hood",
    "screen",
    "shelf",
    "sofa",
    "spoon",
    "spot_light",
    "stool",
    "storage",
    "table",
    "tablecloth",
    "table_lamp",
    "tea_set",
    "television",
    "throw_pillow",
    "tooling",
    "toy",
    "tray",
    "unknown",
    "vase",
    "wall",
    "wall_decoration",
    "wall_light",
    "washing_machine",
    "water_tap",
    "window",
    "wine_set",
]

import csv
import numpy as np


with open("interior_agent_objects.csv", "w", newline="") as f:
    writer = csv.writer(f)
    writer.writerow(["object", "r", "g", "b"])
    for obj in objects:
        color = np.random.rand(3)  # random RGB in [0,1]
        writer.writerow([obj, *color])
